included: # paths to include during linting. `--path` is ignored if present.
  - GSTMobile
  - GSTMobileTests
  - Modules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - External
  - scripts
  - Tuist
  - Project.swift

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - todo
  - xctfail_message
  - identifier_name
  - unused_setter_value
  - orphaned_doc_comment
  - empty_enum_arguments
  - comment_spacing
  - unused_closure_parameter
  - inclusive_language
  - trailing_semicolon
  
opt_in_rules: # some rules are only opt-in
 - attributes
 - closure_end_indentation
 - closure_spacing
 - empty_count
 - explicit_init
 - fatal_error_message
 - file_header
 - first_where
 - force_unwrapping
 - multiline_parameters
 - number_separator
 - object_literal
 - operator_usage_whitespace
 - overridden_super_call
 - prohibited_super_call
 - redundant_nil_coalescing
 - sorted_imports
 - switch_case_on_newline
 - unneeded_parentheses_in_closure_argument
 - vertical_parameter_alignment_on_call
 - file_name_no_space

number_separator:
  minimum_length: 5

trailing_whitespace:
  ignores_comments: true

type_name:
  max_length:
    warning: 60

custom_rules:
  test_convention:
    name: "Unit test naming convention"
    message: "Expected test_MethodName_StateUnderTest_ExpectedBehavior()."
    regex: '(func test_([A-Za-z0-9]+_)*[a-z])'
  tabs_convention:
    name: "Tabs convention is not supported"
    message: "Use spaces instead."
    regex: '\t'
  one_line_convention:
    name: "Line between classes"
    message: "Add new line between each class/struct/enum/extension."
    regex: '^\}+(?!(\n$))'

